development:
  sessions:
    default:
      database: feasted_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: feasted_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: heroku_app14008163
      username: heroku_app14008163
      password: qsuei2025vc1bcs73jetkl1048
      hosts:
        - ds049997.mongolab.com:49997
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
